import java.util.Properties

// Placeholder: plain Kotlin/JVM module, not the Android Gradle Plugin. This
// scaffold exists to prove the polyglot task graph works before the Android
// SDK is provisioned in CI; swap to com.android.application once it is.
plugins {
    kotlin("jvm") version "2.1.0"
    kotlin("plugin.serialization") version "2.1.0"
}

repositories {
    mavenCentral()
}

dependencies {
    // Per AGENTS.md: "use Kotlin coroutines for async code" - the async
    // connect/disconnect calls in the bluetooth package are suspend
    // functions backed by this.
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")

    // MQTT client (ADR 0001). HiveMQ rather than Eclipse Paho: it's a plain
    // Java library that runs both on this module's Kotlin/JVM scaffold and
    // on Android from the same artifact (Paho's Android client is an AAR
    // needing the Android Gradle Plugin, which this module doesn't use yet,
    // and eclipse/paho.mqtt.android is archived/unmaintained), and it
    // supports MQTT-over-WebSocket/TLS - ADR 0001's transport - natively.
    implementation("com.hivemq:hivemq-mqtt-client:1.3.3")

    // JSON for the wire payloads. Needed to encode the manifest's
    // free-text fields with correct escaping and to pin exact field names
    // (@SerialName) against the TypeScript shapes in packages/protocol and
    // packages/relay-core; kotlinx.serialization is the Kotlin-standard,
    // reflection-free (hence Android/R8-friendly) way to do that.
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")

    testImplementation(kotlin("test"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.3")
    testImplementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0")

    // Embedded MQTT broker so the MQTT tests run against a real broker
    // speaking the real protocol, mirroring how packages/relay-core's tests
    // use a real Mosquitto. Moquette is in-process, so unlike Mosquitto it
    // needs no Docker/service container in the CI `android` job.
    testImplementation("io.moquette:moquette-broker:0.17")
    testRuntimeOnly("org.slf4j:slf4j-simple:2.0.16")
}

// ADR 0005: the relay URL and licensing endpoint are build-time
// configuration read from a per-adapter config file, never hardcoded inline
// in source. This generates the Android BuildConfig equivalent from
// ../config/adapter.properties - a self-hoster edits that file and rebuilds.
val adapterConfigFile = rootProject.file("config/adapter.properties")
val generatedConfigDir = layout.buildDirectory.dir("generated/source/adapterConfig")

val generateAdapterBuildConfig =
    tasks.register("generateAdapterBuildConfig") {
        val source = adapterConfigFile
        val outputDir = generatedConfigDir
        inputs.file(source)
        outputs.dir(outputDir)

        doLast {
            val properties = Properties()
            source.inputStream().use { properties.load(it) }

            fun required(key: String): String =
                requireNotNull(properties.getProperty(key)) {
                    "$key missing from ${source.name} - see ADR 0005"
                }

            val packageDir = outputDir.get().asFile.resolve("com/thrw/adapter/android/config")
            packageDir.mkdirs()
            packageDir.resolve("BuildConfig.kt").writeText(
                """
                |// GENERATED by the generateAdapterBuildConfig Gradle task from
                |// packages/adapter-android/config/adapter.properties. Do not edit
                |// by hand and do not commit - edit that properties file instead
                |// (ADR 0005: build-time configuration, not hardcoded endpoints).
                |package com.thrw.adapter.android.config
                |
                |object BuildConfig {
                |    const val RELAY_URL: String = "${required("relay.url")}"
                |    const val LICENSING_URL: String = "${required("licensing.url")}"
                |    const val SELF_HOSTED: Boolean = ${required("selfHosted").toBoolean()}
                |}
                |
                """.trimMargin(),
            )
        }
    }

kotlin.sourceSets.named("main") {
    kotlin.srcDir(generateAdapterBuildConfig)
}

tasks.test {
    useJUnitPlatform()
}
