#!/bin/sh
set -eu

# Generates AdapterBuildConfig.swift from an adapter.properties file.
# Usage: generate.sh <properties-file> <output-swift-file> [local-properties-file]
#
# Mirrors packages/adapter-android/app/build.gradle.kts's
# generateAdapterBuildConfig Gradle task: same properties file format,
# same keys, same "never hardcode this inline" discipline (ADR 0005) -
# SwiftPM's build-tool-plugin mechanism standing in for Gradle's
# arbitrary task type, since SwiftPM has no built-in equivalent (see this
# plugin's own kdoc).
#
# A plain shell script (invoked by the plugin as its prebuildCommand
# executable) rather than logic embedded in the plugin's own Swift code:
# a BuildToolPlugin only *describes* a command to run, it doesn't execute
# arbitrary work itself, so the actual generation has to live in a
# separate executable either way - a shell script needs no extra SwiftPM
# executable target to build and ship alongside the plugin.
#
# #147: the optional third argument is an untracked overlay file
# (config/adapter.local.properties, gitignored). Any key it defines wins
# over the committed adapter.properties. That exists so the relay's MQTT
# credential can be supplied at build time without ever being committed -
# see config/adapter.properties' own comment for the full reasoning.

properties_file="$1"
output_file="$2"
local_properties_file="${3:-}"

# Looks up a key in the overlay first, then the committed file. Prints
# nothing when the key is absent or empty in both.
lookup() {
    key="$1"
    value=""
    if [ -n "$local_properties_file" ] && [ -f "$local_properties_file" ]; then
        value=$(grep -E "^${key}=" "$local_properties_file" | tail -n 1 | cut -d '=' -f2- || true)
    fi
    if [ -z "$value" ]; then
        value=$(grep -E "^${key}=" "$properties_file" | tail -n 1 | cut -d '=' -f2- || true)
    fi
    printf '%s' "$value"
}

get_property() {
    value=$(lookup "$1")
    if [ -z "$value" ]; then
        echo "error: $1 missing from $properties_file - see ADR 0005" >&2
        exit 1
    fi
    printf '%s' "$value"
}

# Credentials are legitimately absent: a local/self-hosted broker with
# allow_anonymous on needs none, and that's how this package's own tests
# and CI run. Empty means "connect anonymously", not "misconfigured".
get_optional_property() {
    lookup "$1"
}

# Escapes the two characters that would otherwise break out of the Swift
# string literal below. Credentials are arbitrary text - a password
# containing a quote or backslash must not produce uncompilable source.
escape_for_swift() {
    printf '%s' "$1" | sed -e 's/\\/\\\\/g' -e 's/"/\\"/g'
}

relay_url=$(get_property 'relay\.url')
licensing_url=$(get_property 'licensing\.url')
self_hosted=$(get_property 'selfHosted')
relay_username=$(escape_for_swift "$(get_optional_property 'relay\.username')")
relay_password=$(escape_for_swift "$(get_optional_property 'relay\.password')")

case "$self_hosted" in
    true) self_hosted_literal="true" ;;
    false) self_hosted_literal="false" ;;
    *)
        echo "error: selfHosted must be 'true' or 'false' in $properties_file, got '$self_hosted'" >&2
        exit 1
        ;;
esac

mkdir -p "$(dirname "$output_file")"
cat > "$output_file" <<EOF
// GENERATED by GenerateAdapterConfigPlugin from
// packages/adapter-mac/config/adapter.properties (overlaid by
// adapter.local.properties when present). Do not edit by hand and do not
// commit - edit those properties files instead (ADR 0005: build-time
// configuration, not hardcoded endpoints).
enum AdapterBuildConfig {
    static let relayURL: String = "$relay_url"
    static let licensingURL: String = "$licensing_url"
    static let selfHosted: Bool = $self_hosted_literal
    /// Empty when unset - see \`RelayCredentials.fromBuildConfig()\`.
    static let relayUsername: String = "$relay_username"
    static let relayPassword: String = "$relay_password"
}
EOF
