#!/bin/sh
set -eu

# Generates AdapterBuildConfig.swift from an adapter.properties file.
# Usage: generate.sh <properties-file> <output-swift-file>
#
# Mirrors packages/adapter-android/app/build.gradle.kts's
# generateAdapterBuildConfig Gradle task: same properties file format,
# same three keys (relay.url / licensing.url / selfHosted), same "never
# hardcode this inline" discipline (ADR 0005) - SwiftPM's build-tool-
# plugin mechanism standing in for Gradle's arbitrary task type, since
# SwiftPM has no built-in equivalent (see this plugin's own kdoc).
#
# A plain shell script (invoked by the plugin as its prebuildCommand
# executable) rather than logic embedded in the plugin's own Swift code:
# a BuildToolPlugin only *describes* a command to run, it doesn't execute
# arbitrary work itself, so the actual generation has to live in a
# separate executable either way - a shell script needs no extra SwiftPM
# executable target to build and ship alongside the plugin.

properties_file="$1"
output_file="$2"

get_property() {
    key="$1"
    value=$(grep -E "^${key}=" "$properties_file" | tail -n 1 | cut -d '=' -f2-)
    if [ -z "$value" ]; then
        echo "error: $key missing from $properties_file - see ADR 0005" >&2
        exit 1
    fi
    printf '%s' "$value"
}

relay_url=$(get_property 'relay\.url')
licensing_url=$(get_property 'licensing\.url')
self_hosted=$(get_property 'selfHosted')

case "$self_hosted" in
    true) self_hosted_literal="true" ;;
    false) self_hosted_literal="false" ;;
    *)
        echo "error: selfHosted must be 'true' or 'false' in $properties_file, got '$self_hosted'" >&2
        exit 1
        ;;
esac

mkdir -p "$(dirname "$output_file")"
cat > "$output_file" <<EOF
// GENERATED by GenerateAdapterConfigPlugin from
// packages/adapter-mac/config/adapter.properties. Do not edit by hand and
// do not commit - edit that properties file instead (ADR 0005: build-time
// configuration, not hardcoded endpoints).
enum AdapterBuildConfig {
    static let relayURL: String = "$relay_url"
    static let licensingURL: String = "$licensing_url"
    static let selfHosted: Bool = $self_hosted_literal
}
EOF
